package com.github.jhonnymertz.wkhtmltopdf.wrapper.configurations;

import java.io.File;
import java.io.FilenameFilter;

/**
 * Implements a filter to get files generated by the library
 */
public class FilenameFilterConfig implements FilenameFilter {
    @Override
    public boolean accept(File dir, String name) {
        return name.matches("java-wkhtmltopdf-wrapper.*");
    }
}
